// <auto-generated />
using System;
using Datos.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Datos.Migrations
{
    [DbContext(typeof(HospitalBDContext))]
    [Migration("20240803160109_InitialSecurityMigration")]
    partial class InitialSecurityMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.7");

            modelBuilder.Entity("Datos.Entities.Roles", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            id = 1,
                            name = "Administrador"
                        },
                        new
                        {
                            id = 2,
                            name = "Doctor"
                        },
                        new
                        {
                            id = 3,
                            name = "Cliente"
                        });
                });

            modelBuilder.Entity("Datos.Entities.Users", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("creadoEn")
                        .HasColumnType("TEXT");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("role_id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("role_id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            id = 1,
                            creadoEn = new DateTime(2024, 8, 3, 12, 1, 7, 611, DateTimeKind.Local).AddTicks(1140),
                            password = "12345",
                            role_id = 1,
                            username = "admin_test"
                        },
                        new
                        {
                            id = 2,
                            creadoEn = new DateTime(2024, 8, 3, 12, 1, 7, 611, DateTimeKind.Local).AddTicks(1160),
                            password = "12345",
                            role_id = 2,
                            username = "doctor_test"
                        },
                        new
                        {
                            id = 3,
                            creadoEn = new DateTime(2024, 8, 3, 12, 1, 7, 611, DateTimeKind.Local).AddTicks(1163),
                            password = "12345",
                            role_id = 3,
                            username = "client_test"
                        });
                });

            modelBuilder.Entity("Datos.Entities.Users", b =>
                {
                    b.HasOne("Datos.Entities.Roles", "role")
                        .WithMany()
                        .HasForeignKey("role_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("role");
                });
#pragma warning restore 612, 618
        }
    }
}
