// <auto-generated />
using System;
using Datos.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Datos.Migrations
{
    [DbContext(typeof(HospitalBDContext))]
    [Migration("20240805234642_SchedIntegrated")]
    partial class SchedIntegrated
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.7");

            modelBuilder.Entity("Datos.Entities.Doctors", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("fechaInicio")
                        .HasColumnType("TEXT");

                    b.Property<string>("fullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("telefono")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("user_id")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("user_id");

                    b.ToTable("Doctors");
                });

            modelBuilder.Entity("Datos.Entities.Especialities", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("active")
                        .HasColumnType("INTEGER");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Especialities");
                });

            modelBuilder.Entity("Datos.Entities.Roles", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            id = 1,
                            name = "Administrador"
                        },
                        new
                        {
                            id = 2,
                            name = "Doctor"
                        },
                        new
                        {
                            id = 3,
                            name = "Cliente"
                        });
                });

            modelBuilder.Entity("Datos.Entities.SchedulesRegister", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DoctorsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.HasIndex("DoctorsId");

                    b.ToTable("SchedulesRegister");
                });

            modelBuilder.Entity("Datos.Entities.SchedulesSystem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("finalHour")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("initHour")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SchedulesSystems");
                });

            modelBuilder.Entity("Datos.Entities.Users", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("creadoEn")
                        .HasColumnType("TEXT");

                    b.Property<string>("password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("role_id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.HasIndex("role_id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            id = 1,
                            creadoEn = new DateTime(2024, 8, 5, 19, 46, 41, 695, DateTimeKind.Local).AddTicks(4072),
                            password = "12345",
                            role_id = 1,
                            username = "admin_test"
                        },
                        new
                        {
                            id = 2,
                            creadoEn = new DateTime(2024, 8, 5, 19, 46, 41, 695, DateTimeKind.Local).AddTicks(4085),
                            password = "12345",
                            role_id = 2,
                            username = "doctor_test"
                        },
                        new
                        {
                            id = 3,
                            creadoEn = new DateTime(2024, 8, 5, 19, 46, 41, 695, DateTimeKind.Local).AddTicks(4087),
                            password = "12345",
                            role_id = 3,
                            username = "client_test"
                        });
                });

            modelBuilder.Entity("Datos.Entities.Doctors", b =>
                {
                    b.HasOne("Datos.Entities.Users", "user")
                        .WithMany()
                        .HasForeignKey("user_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("user");
                });

            modelBuilder.Entity("Datos.Entities.SchedulesRegister", b =>
                {
                    b.HasOne("Datos.Entities.Doctors", null)
                        .WithMany("schedules")
                        .HasForeignKey("DoctorsId");
                });

            modelBuilder.Entity("Datos.Entities.Users", b =>
                {
                    b.HasOne("Datos.Entities.Roles", "role")
                        .WithMany()
                        .HasForeignKey("role_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("role");
                });

            modelBuilder.Entity("Datos.Entities.Doctors", b =>
                {
                    b.Navigation("schedules");
                });
#pragma warning restore 612, 618
        }
    }
}
